/* Sapphic Weekly ATX — Halloween zodiac content.
   Pools marked SAMPLE are complete. Signs/pairings not written yet fall back to draft text.
   Pairing keys are "lowerSignIndex-higherSignIndex" (Aries=0 … Pisces=11). Each pairing needs
   exactly 23 compat + 23 wary lines; each facts list needs exactly 23 lines. */
window.CONTENT = {
  horoscopes: {
    Virgo: {
      vibe: [
        "Your drink will be exactly right tonight, which is suspicious, because nothing is ever exactly right. Accept it.",
        "Someone is going to compliment the thing you spent forty minutes adjusting in the mirror. Let them.",
        "The cutie across the room noticed you first. Stop auditing your outfit and go say hi.",
        "Tonight rewards the Virgo who puts the phone away after this and actually stays in the moment.",
        "A conversation you almost skip turns into the best one of the night. Don't skip it.",
        "Your standards are high and tonight someone meets them. Try not to look surprised.",
        "You'll catch yourself having fun without a plan. Analyze it tomorrow, not now.",
        "A great drink, a better laugh, and one person who gets your humor on the first try.",
        "One more drink than you planned, one less worry than you brought.",
        "Someone here needs your advice tonight. Give it kindly, then go dance.",
        "Your quiet observations are hilarious tonight. Say them out loud for once.",
        "You'll leave with a new number and zero regrets about how you asked for it.",
        "Tonight is for small lovely things: a good song, a warm laugh, a stranger's great earrings.",
        "You'll meet someone who's as organized as you pretend to be. Respect.",
        "Let someone else pick the next drink. A little chaos looks good on you tonight.",
        "A flirty moment arrives the second you stop rehearsing what to say.",
        "Your energy is calm, magnetic, and a little witchy. Perfect for October.",
        "The stars predict one excellent photo of you tonight. You'll hate it for a second, then love it.",
        "You came to have fun, not to fix anyone's life. Remember that at the bar.",
        "Something small and sweet happens near the end of the night. Stay long enough to catch it."
      ],
      creature: [
        "Witch 🧙‍♀️ You brew your own luck, and tonight someone notices the spell.",
        "Ghost 👻 You glide in quietly and somehow know everyone's business by 10pm.",
        "Vampire 🦇 Candlelit elegance, impeccable standards, and you only bite when invited.",
        "Black cat 🐈‍⬛ Aloof at first, affectionate once someone earns it.",
        "Mothwoman 🦋 Drawn to the one warm light in the room. Go find her.",
        "Werewolf 🐺 Perfectly composed until one particular song comes on.",
        "Siren 🧜‍♀️ Your voice, your gaze, your terrible puns: all irresistible tonight.",
        "Mummy 🧻 Wrapped up tight, but one good conversation unravels you."
      ],
      warning: [
        "Don't correct anyone's astrology before they've finished their drink.",
        "That text you're overthinking is fine. Mercury isn't even in retrograde.",
        "Beware of Sagittarius tonight. They will talk you into one more place.",
        "Your inner critic RSVP'd. Tell her the event is at capacity.",
        "Beware of Gemini: two conversations will turn into four and you'll lose your drink.",
        "Do not reorganize the venue's napkins. We see you.",
        "Beware of Pisces bearing compliments. You will believe every single one.",
        "The stars warn against leaving early \"to be responsible.\" Stay for one more song."
      ]
    }
  },

  facts: {
    Virgo: [
      "Virgos have been known to mentally edit your text messages while you're still typing.",
      "Virgos notice your new haircut before anyone else does.",
      "Virgos have been known to say \"I'm fine\" while quietly fixing everything around them.",
      "Virgos own a label maker and have strong feelings about it.",
      "Virgos will remember your cat's name from a conversation six months ago.",
      "Virgos have been known to read the reviews for a restaurant they've already been to.",
      "Virgos show love by sending you the article you mentioned once.",
      "Virgos will clean your kitchen at your party and call it relaxing.",
      "Virgos have been known to rehearse casual conversations. Possibly this one.",
      "Virgos can spot a typo from across the room.",
      "Virgos secretly want you to ask about their skincare routine.",
      "Virgos have been known to arrive early, then circle the block so they don't look early.",
      "Virgos have opinions about how you load a dishwasher. Don't ask unless you're ready.",
      "Virgos are the friend with band-aids, a charger, and a spare snack in their bag.",
      "Virgos will notice you're sad before you say a word.",
      "Virgos have been known to write pro/con lists about crushes.",
      "Virgos have a twelve-step skincare routine and a one-step emotional routine: overthink.",
      "Virgos get flirtier the more organized the room is.",
      "Virgos have been known to fold a receipt into a perfect little square mid-conversation.",
      "Virgos have been known to plan a spontaneous trip down to the minute.",
      "Virgos are secretly the funniest person in the group chat.",
      "Virgos will pretend they didn't plan their outfit. They planned their outfit.",
      "Virgos fall hard and quietly, then deny it for months."
    ],
    Aries: [
      "Aries have been known to start a group chat, a band, and a feud in the same week.",
      "Aries will race you to the bar and then insist on paying.",
      "Aries have been known to text \"on my way\" before they've found their shoes.",
      "Aries get competitive about games that don't have a winner.",
      "Aries fall in love fast and loudly. You'll know.",
      "Aries have been known to say the thing everyone else was only thinking.",
      "Aries will take you on a spontaneous 1am taco run and call it a date.",
      "Aries have been known to lose their keys and make a new best friend in the same five minutes.",
      "Aries hate waiting in line and will befriend everyone in it anyway.",
      "Aries have been known to challenge strangers to arm wrestling. Decline or commit fully.",
      "Aries apologize fast, forget faster, and hold zero grudges.",
      "Aries find the dance floor within ninety seconds of arriving anywhere.",
      "Aries get bored three minutes into a movie trailer.",
      "Aries will defend you in an argument you didn't know you were in.",
      "Aries have been known to book the flight before asking for the time off.",
      "Aries treat flirting like a sport, and they are not playing for fun.",
      "Aries have a hot temper and a warm heart, usually at the same moment.",
      "Aries have been known to order the spiciest thing on the menu out of spite.",
      "Aries make the first move so fast you'll wonder if you imagined it.",
      "Aries will absolutely start karaoke if nobody stops them.",
      "Aries have been known to quit a hobby in a week and keep all the gear forever.",
      "Aries think a five-minute walk is a quick run.",
      "Aries will hype you up like your personal cheer squad."
    ]
  },

  pairings: {
    "0-5": { // Aries × Virgo
      compat: [
        "Aries leaps, Virgo checks the landing. Together you actually stick it.",
        "One brings the spark, the other brings the fire extinguisher. Somehow, it's flirty.",
        "Aries wants to go now. Virgo wants to know where. The answer is somewhere fun.",
        "Different speeds, same loyalty. Once you're in, you're in.",
        "Aries makes Virgo laugh at her own rules. Virgo makes Aries finish a sentence.",
        "You're the plan and the plot twist. Great for stories, chaotic for calendars.",
        "Aries admires Virgo's calm. Virgo secretly admires Aries' nerve.",
        "This match runs on banter. Expect to roast each other within five minutes.",
        "One of you says \"let's just go.\" The other has already mapped the route.",
        "Aries brings the dare, Virgo brings the details. That's a heist movie.",
        "Aries is the firework, Virgo read the safety instructions. You both enjoy the show.",
        "Opposite tempos, identical stubbornness. Great debates ahead.",
        "You'll disagree about how to order drinks and agree on nearly everything else.",
        "Aries teaches Virgo to jump. Virgo teaches Aries to look first. Growth, babe.",
        "Fire meets earth: a few scorch marks, but also a very cozy campfire.",
        "This is more chess than checkers, except Aries keeps flipping the board.",
        "An unlikely duo that would absolutely win a scavenger hunt.",
        "Aries is loud about liking you. Virgo shows it in quiet little favors. Both count.",
        "Instant friction, instant chemistry. Hard to tell which came first.",
        "You bring out each other's competitive streak. Maybe keep score tonight.",
        "Aries sets the pace, Virgo sets the standard. Meet in the middle, near the bar.",
        "Tricky on paper, fun in person.",
        "One impulsive, one precise. Together you're impulsively precise."
      ],
      wary: [
        "Aries will interrupt. Virgo will notice. Keep score the fun way, not the real way.",
        "Don't let a flirty debate turn into an actual debate.",
        "Beware the phrase \"well, actually.\" Neither of you will survive it.",
        "\"Let's wing it\" meets \"have we thought about this.\" Pick one per night.",
        "Don't race for the last word. There is no last word.",
        "Virgo critique plus Aries pride equals a spicy moment. Lead with compliments.",
        "Be careful making plans at midnight. One of you will actually follow up.",
        "Aries gets bored fast, Virgo gets hurt quietly. Say things out loud.",
        "Watch for Aries ordering a round of shots Virgo didn't schedule.",
        "Don't compete over who's more \"fine.\" Neither of you is.",
        "Don't let one tiny detail start a big argument. It's a party.",
        "Aries may hear Virgo's tips as criticism. Wrap them in a joke.",
        "Speed mismatch alert: one of you is already on the dance floor.",
        "Beware the \"who's driving\" conversation. Settle it early.",
        "Virgo may overthink Aries' bluntness. It wasn't that deep.",
        "Aries may read Virgo's quiet as disinterest. It's not. She's taking notes.",
        "Don't challenge each other to anything. You'll both commit way too hard.",
        "Don't correct each other's stories in front of people. Save it for the car.",
        "This match can go from flirting to bickering in one drink. Hydrate.",
        "Don't leave the planning to Aries or the vibe to Virgo. Swap roles.",
        "Aries' temper plus Virgo's side-eye makes one dramatic glare. Laugh it off.",
        "Don't try to fix each other before the second drink.",
        "Don't get so into the banter that you forget to trade numbers."
      ]
    },
    "5-5": { // Virgo × Virgo
      compat: [
        "Finally, someone else who noticed the crooked picture frame.",
        "You'll bond instantly over something tiny, like the font on the menu.",
        "A match made in a color-coded calendar.",
        "Mutual respect, mutual overthinking, mutual crushes you'll both deny.",
        "You'll get each other's inside jokes before they're even jokes.",
        "Two helpers in one room means someone finally takes care of the Virgo.",
        "Calm, clever, and dangerously good at analyzing the gossip.",
        "You speak the same language: sarcasm, lists, and quiet devotion.",
        "This is \"we should start a business together\" chemistry.",
        "Two perfectionists who somehow make each other relax. Wild, but it happens.",
        "Expect this conversation to go deep much faster than either of you planned.",
        "You'll both pretend you're not tracking who texts first.",
        "Double the standards, double the loyalty.",
        "Cozy energy: tea, a good playlist, and a reorganized bookshelf.",
        "You'll finish each other's corrections.",
        "Grounded and gentle together. The earth-sign version of a weighted blanket.",
        "Your humor is so dry together it's a fire hazard.",
        "Somehow you both brought the same backup lip balm.",
        "Two Virgos, zero wasted words. Every sentence counts.",
        "By the end of the night you'll have analyzed the entire party together.",
        "Fellow planner found. Your future brunches will run on time.",
        "Low drama, high substance. Rare at a bar.",
        "Mirror energy: you'll see yourself in her and actually like it."
      ],
      wary: [
        "Don't critique each other's critiques. It's a loop.",
        "You'll both wait for the other to make the first move. Someone has to.",
        "Two overthinkers can turn one text into a four-day saga.",
        "Don't compete over who's more helpful. Let her help you.",
        "Don't spend the whole night analyzing everyone else. Talk about yourselves.",
        "Don't plan the second date before the first conversation ends.",
        "You both apologize too much. Stop saying sorry to each other.",
        "Beware the \"I'm fine\" standoff. Somebody break first.",
        "Don't let perfectionism kill the fun. Messy is allowed tonight.",
        "Don't correct each other's grammar in texts. Flirt first, edit later.",
        "Two Virgos can talk themselves out of anything. Don't talk yourselves out of this.",
        "Don't turn this into a productivity seminar.",
        "Watch for silent judgment spirals, yours and hers.",
        "Don't try to out-organize each other's lives.",
        "Don't assume she's not interested. She's just being a Virgo.",
        "Don't split the bill to the cent. Round up and move on.",
        "Don't mirror each other's worries. One of you has to be the calm one.",
        "Don't schedule the fun. Let some of it just happen.",
        "Critical minds, soft hearts. Don't forget the soft part.",
        "Beware your shared habit of leaving early. Stay.",
        "You'll both notice every tiny flaw. Agree to ignore them together.",
        "Don't keep it too safe. Ask a real question.",
        "Beware of both saying \"we should hang out\" and neither sending the text."
      ]
    }
  },

  icebreakers: [
    "What's the most chaotic thing you've done this year?",
    "If you were a Halloween candy, which one and why?",
    "What's your most controversial take on a popular show?",
    "What's a small thing that instantly makes your day better?",
    "What would your villain origin story be?",
    "What's the best date you've ever been on, or planned?",
    "What song would you make the DJ play right now?",
    "What's your go-to karaoke song, and have you actually performed it?",
    "If you could haunt one place for a year, where would it be?",
    "What's the weirdest thing you believe in?",
    "What's your most useless talent?",
    "What costume have you always wanted to wear but haven't yet?",
    "What's the best thing about being queer in Austin?",
    "What's a red flag of yours that's actually a green flag?",
    "What's the last thing that made you laugh out loud?",
    "What are you weirdly competitive about?",
    "What does your ideal Sunday look like?",
    "Which fictional character was your first crush?",
    "What hobby did you pick up and drop almost immediately?",
    "What's the scariest movie you've actually enjoyed?",
    "What would your friends say you're famous for?",
    "If your life had a theme song, what would it be?",
    "What's your most-used emoji, and what does it say about you?",
    "What's a hill you'd die on?",
    "What's the best advice you've ever ignored?",
    "What's your 2am comfort food?",
    "What's on your bucket list that you haven't told many people?",
    "Honestly, which sign do you think you're most compatible with?",
    "What's the most spontaneous thing you've ever done?",
    "What's your favorite Austin spot that tourists don't know about?",
    "If you could swap lives with anyone here for one night, who would it be?",
    "What's your best worst pickup line?",
    "What's a tiny luxury you refuse to give up?",
    "What are you proud of that nobody ever asks you about?",
    "What's the pettiest reason you've stopped seeing someone?",
    "If you were a ghost, how would you mess with people?",
    "What's your spooky season tradition?",
    "What's the best thing that happened to you this week?",
    "Vampire, witch, or werewolf: which one would you date?",
    "What always gets you on the dance floor?",
    "What's the last thing you got really excited about?"
  ],

  finale: {
    gravitated: {
      Aries: "You clearly like a little chaos in your cup.",
      Taurus: "Cozy, loyal, and probably holding snacks. Solid choice.",
      Gemini: "You like your conversations with a plot twist every thirty seconds.",
      Cancer: "You found the softest hearts in the room. Protect them.",
      Leo: "You kept orbiting the main characters. Honestly, same.",
      Virgo: "You were drawn to people who notice everything. Hope your outfit was on point.",
      Libra: "You followed the charm. Who could blame you?",
      Scorpio: "You like a little mystery. Dangerous. We love it.",
      Sagittarius: "You chased the adventure all night. Someone's getting a travel buddy.",
      Capricorn: "You gravitated to the ones with a five-year plan. Ambitious of you.",
      Aquarius: "You like the weird ones. They like you back.",
      Pisces: "You floated toward the dreamers. Very poetic of you."
    },
    soulmate: {
      Aries: "Your cosmic match is pure fire. Keep a glass of water nearby.",
      Taurus: "Your soulmate sign brings stability and probably a charcuterie board.",
      Gemini: "Your perfect match can talk you into anything. Proceed with delight.",
      Cancer: "Your soulmate sign will remember your birthday and your mom's.",
      Leo: "Your cosmic match will hype you up louder than anyone here.",
      Virgo: "Your soulmate sign already noticed what you're wearing.",
      Libra: "Your cosmic match has great taste. Including in you.",
      Scorpio: "Your soulmate sign knows exactly what you're thinking. Gulp.",
      Sagittarius: "Your cosmic match will plan the road trip. You bring the snacks.",
      Capricorn: "Your soulmate sign has a plan, and you're in it.",
      Aquarius: "Your cosmic match is delightfully weird. Don't let her float away.",
      Pisces: "Your soulmate sign will write a poem about tonight."
    }
  }
};
